version: '3.3'
services:
  tabletop-online:
    image: tabletop-online:latest
    ports:
      - '80:8080'
    # volumes:
    build:
      context: .
    restart: always
    logging:
      options:
        max-size: 1g
